name: 'qversity'
version: '1.0.0'
config-version: 2

profile: 'qversity'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
analysis-paths: ["analysis"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  qversity:
    # Solo mantenemos silver por ahora
    silver:
      +materialized: table
      +schema: silver


seeds:
  qversity:
    +schema: raw
